# Generated by Django 4.1.3 on 2024-06-23 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Authors',
            },
        ),
        migrations.CreateModel(
            name='BlogCardButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(null=True)),
                ('ImageURL', models.CharField(max_length=1500)),
                ('title', models.CharField(max_length=500)),
                ('body', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Blog Button Card',
            },
        ),
        migrations.CreateModel(
            name='Creamcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(null=True)),
                ('ImageURL', models.CharField(max_length=1500)),
                ('title', models.CharField(max_length=500)),
                ('body', models.TextField(blank=True, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Quizapp2.author')),
            ],
            options={
                'verbose_name_plural': 'Cream Cards',
            },
        ),
        migrations.CreateModel(
            name='NotesCardsCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('topic', models.CharField(blank=True, max_length=255, null=True)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuizQuestionCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=255)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Subjects',
            },
        ),
        migrations.CreateModel(
            name='Trending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topics', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Trending Topics',
            },
        ),
        migrations.CreateModel(
            name='TrendingArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('year', models.CharField(choices=[('2021', '2021'), ('2022', '2022'), ('2023', '2023')], default=2023, max_length=4)),
                ('month', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=12)),
                ('topics', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Trending Topics Archives',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='Quizapp2.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=255)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('membership', models.CharField(choices=[('P', 'Premium'), ('F', 'Free')], default='F', max_length=1)),
                ('date_joined', models.DateTimeField(auto_now_add=True, null=True)),
                ('correct_incorrect_data', models.CharField(default='1,2,3', max_length=20)),
                ('accuracy_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cards_read', models.PositiveIntegerField(default=0)),
                ('saved_cards', models.ManyToManyField(blank=True, related_name='saved_by', to='Quizapp2.creamcard')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__first_name', 'user__last_name'],
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(null=True)),
                ('preview_text', models.CharField(max_length=255)),
                ('questionText', models.TextField()),
                ('option_1', models.CharField(max_length=510)),
                ('option_2', models.CharField(max_length=510)),
                ('option_3', models.CharField(max_length=510)),
                ('option_4', models.CharField(max_length=510)),
                ('isACorrect', models.BooleanField(default=False)),
                ('isBCorrect', models.BooleanField(default=False)),
                ('isCCorrect', models.BooleanField(default=False)),
                ('isDCorrect', models.BooleanField(default=False)),
                ('correctCount', models.IntegerField(blank=True, default=1, null=True)),
                ('inCorrectCount', models.IntegerField(blank=True, default=1, null=True)),
                ('explanation', models.TextField()),
                ('collection', models.ManyToManyField(blank=True, related_name='collection_questions', to='Quizapp2.quizquestioncollection')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Quizapp2.subject')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Quizapp2.topic')),
            ],
            options={
                'verbose_name_plural': 'Quiz Questions',
                'ordering': ['subject'],
            },
        ),
        migrations.CreateModel(
            name='NotesCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(null=True)),
                ('title', models.CharField(max_length=500)),
                ('body', models.TextField(blank=True, null=True)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Quizapp2.subject')),
            ],
            options={
                'verbose_name_plural': 'NotesCards',
            },
        ),
        migrations.CreateModel(
            name='FLTCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('tests', models.ManyToManyField(to='Quizapp2.quizquestioncollection')),
            ],
            options={
                'verbose_name_plural': 'FLT Collections',
            },
        ),
        migrations.AddField(
            model_name='creamcard',
            name='related_quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Quizapp2.quizquestioncollection'),
        ),
        migrations.AddField(
            model_name='creamcard',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Quizapp2.subject'),
        ),
        migrations.CreateModel(
            name='Accuracy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_attempt', models.IntegerField(default=1)),
                ('incorrect_attempt', models.IntegerField(default=1)),
                ('total', models.IntegerField(default=2)),
                ('percentage', models.DecimalField(decimal_places=2, default=50, max_digits=10)),
                ('student', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Quizapp2.student')),
            ],
            options={
                'verbose_name_plural': 'Accuracy',
            },
        ),
    ]
