# Generated by Django 4.1.3 on 2022-12-26 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Authors',
            },
        ),
        migrations.CreateModel(
            name='Creamcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(null=True)),
                ('ImageURL', models.CharField(max_length=1500)),
                ('title', models.CharField(max_length=500)),
                ('body', models.TextField(blank=True, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Quizapp2.author')),
            ],
            options={
                'verbose_name_plural': 'Cream Cards',
            },
        ),
        migrations.CreateModel(
            name='QuizQuestionCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Subjects',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='Quizapp2.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=255)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('membership', models.CharField(choices=[('P', 'Premium'), ('F', 'Free')], default='F', max_length=1)),
                ('date_joined', models.DateTimeField(auto_now_add=True, null=True)),
                ('saved_cards', models.ManyToManyField(blank=True, related_name='saved_by', to='Quizapp2.creamcard')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__first_name', 'user__last_name'],
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(null=True)),
                ('preview_text', models.CharField(max_length=255)),
                ('questionText', models.TextField()),
                ('option_1', models.CharField(max_length=510)),
                ('option_2', models.CharField(max_length=510)),
                ('option_3', models.CharField(max_length=510)),
                ('option_4', models.CharField(max_length=510)),
                ('isACorrect', models.BooleanField(default=False)),
                ('isBCorrect', models.BooleanField(default=False)),
                ('isCCorrect', models.BooleanField(default=False)),
                ('isDCorrect', models.BooleanField(default=False)),
                ('correctCount', models.IntegerField(blank=True, default=1, null=True)),
                ('inCorrectCount', models.IntegerField(blank=True, default=1, null=True)),
                ('explanation', models.TextField()),
                ('collection', models.ManyToManyField(blank=True, related_name='collection_questions', to='Quizapp2.quizquestioncollection')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Quizapp2.subject')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Quizapp2.topic')),
            ],
            options={
                'verbose_name_plural': 'Quiz Questions',
                'ordering': ['subject'],
            },
        ),
        migrations.AddField(
            model_name='creamcard',
            name='related_quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Quizapp2.quizquestioncollection'),
        ),
        migrations.AddField(
            model_name='creamcard',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Quizapp2.subject'),
        ),
        migrations.CreateModel(
            name='Accuracy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_attempt', models.IntegerField(default=1)),
                ('incorrect_attempt', models.IntegerField(default=1)),
                ('total', models.IntegerField(default=2)),
                ('percentage', models.DecimalField(decimal_places=2, default=50, max_digits=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Accuracy',
            },
        ),
    ]
