# Generated by Django 4.1.3 on 2024-06-23 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quizapp2', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotesCardsCollection',
        ),
    ]
