# Generated by Django 4.1.3 on 2022-11-12 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quizapp2', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creamcards',
            name='status',
        ),
    ]
