# Generated by Django 4.1.3 on 2022-12-26 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Quizapp2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='accuracy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Quizapp2.accuracy'),
            preserve_default=False,
        ),
    ]
