# Generated by Django 4.1.3 on 2023-01-16 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizapp2', '0002_fltcollection'),
    ]

    operations = [
        migrations.AddField(
            model_name='fltcollection',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
