# Generated by Django 4.1.3 on 2022-11-14 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizapp2', '0002_remove_creamcards_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creamcards',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
    ]
