# Generated by Django 4.1.3 on 2024-06-23 13:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Quizapp2', '0002_delete_notescardscollection'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotesCardsCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('topic', models.CharField(blank=True, max_length=255, null=True)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
