# Generated by Django 4.1.3 on 2022-12-27 11:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Quizapp2', '0002_student_accuracy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='accuracy',
        ),
        migrations.AlterField(
            model_name='accuracy',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='accuracy', to=settings.AUTH_USER_MODEL),
        ),
    ]
