# Generated by Django 4.1.3 on 2022-12-27 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Quizapp2', '0003_remove_student_accuracy_alter_accuracy_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='accuracy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Quizapp2.accuracy'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accuracy',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
