# Generated by Django 4.1.3 on 2023-01-16 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizapp2', '0003_fltcollection_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestioncollection',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
