# Generated by Django 4.1.3 on 2024-06-23 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizapp2', '0004_alter_notescardscollection_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='notescard',
            name='collection',
            field=models.ManyToManyField(blank=True, related_name='notes_cards', to='Quizapp2.notescardscollection'),
        ),
    ]
