# Generated by Django 4.1.3 on 2023-01-16 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quizapp2', '0004_quizquestioncollection_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizquestioncollection',
            name='description',
        ),
    ]
