# Generated by Django 4.1.3 on 2022-11-15 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quizapp2', '0004_topic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuizQuestions',
        ),
    ]
