# Generated by Django 4.1.3 on 2024-06-23 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Quizapp2', '0005_notescard_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='creamcard',
            name='related_notes_collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Quizapp2.notescardscollection'),
        ),
    ]
