# Generated by Django 4.1.3 on 2023-01-16 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizapp2', '0005_remove_quizquestioncollection_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='fltcollection',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
