# Generated by Django 4.1.3 on 2022-11-15 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Quizapp2', '0005_delete_quizquestions'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(null=True)),
                ('preview_text', models.CharField(max_length=255)),
                ('questionText', models.TextField()),
                ('option_1', models.CharField(max_length=510)),
                ('option_2', models.CharField(max_length=510)),
                ('option_3', models.CharField(max_length=510)),
                ('option_4', models.CharField(max_length=510)),
                ('isACorrect', models.BooleanField(default=False)),
                ('isBorrect', models.BooleanField(default=False)),
                ('isCCorrect', models.BooleanField(default=False)),
                ('isDCorrect', models.BooleanField(default=False)),
                ('explanation', models.TextField()),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_questions', to='Quizapp2.topic')),
            ],
            options={
                'verbose_name_plural': 'Quiz Questions',
            },
        ),
    ]
