# Generated by Django 4.1.3 on 2022-11-15 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizapp2', '0006_quizquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizQuestionCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('questions', models.ManyToManyField(blank=True, related_name='collection', to='Quizapp2.quizquestion')),
            ],
        ),
    ]
