# Generated by Django 4.1.3 on 2023-01-16 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizapp2', '0006_fltcollection_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestioncollection',
            name='subject',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
