# Generated by Django 4.1.3 on 2022-11-15 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Quizapp2', '0007_quizquestioncollection'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_questions', to='Quizapp2.subjects'),
        ),
    ]
