# Generated by Django 4.1.3 on 2023-01-17 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizapp2', '0007_quizquestioncollection_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrendingArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(choices=[(2021, '2021'), (2022, '2022'), (2023, '2023')], default=2023, max_length=4)),
                ('month', models.CharField(choices=[(2021, '2021'), (2022, '2022'), (2023, '2023')], max_length=3)),
                ('topics', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='fltcollection',
            options={'verbose_name_plural': 'FLT Collections'},
        ),
    ]
