# Generated by Django 4.1.3 on 2022-11-15 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizapp2', '0008_quizquestion_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizquestioncollection',
            name='questions',
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='collection',
            field=models.ManyToManyField(blank=True, related_name='Question', to='Quizapp2.quizquestioncollection'),
        ),
    ]
