# Generated by Django 4.1.3 on 2022-11-15 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizapp2', '0009_remove_quizquestioncollection_questions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizquestion',
            name='collection',
            field=models.ManyToManyField(blank=True, related_name='collection_questions', to='Quizapp2.quizquestioncollection'),
        ),
    ]
