# Generated by Django 4.1.3 on 2022-11-15 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quizapp2', '0010_alter_quizquestion_collection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizquestion',
            name='collection',
        ),
    ]
