# Generated by Django 4.1.3 on 2023-01-17 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizapp2', '0010_alter_trendingarchive_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trendingarchive',
            name='year',
            field=models.CharField(choices=[('2021', '2021'), ('2022', '2022'), ('2023', '2023')], default=2023, max_length=4),
        ),
    ]
