# Generated by Django 4.1.3 on 2023-01-17 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizapp2', '0011_alter_trendingarchive_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trendingarchive',
            options={'ordering': ['updated_at'], 'verbose_name_plural': 'Trending Topics Archives'},
        ),
        migrations.AddField(
            model_name='trendingarchive',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
