# Generated by Django 4.1.3 on 2022-11-15 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizapp2', '0011_remove_quizquestion_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestioncollection',
            name='questions',
            field=models.ManyToManyField(related_name='collection', to='Quizapp2.quizquestion'),
        ),
    ]
