# Generated by Django 4.1.3 on 2022-11-15 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quizapp2', '0012_quizquestioncollection_questions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quizquestion',
            options={'ordering': ['subject'], 'verbose_name_plural': 'Quiz Questions'},
        ),
    ]
