# Generated by Django 4.1.3 on 2022-11-15 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quizapp2', '0013_alter_quizquestion_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizquestioncollection',
            name='questions',
        ),
    ]
