# Generated by Django 4.1.3 on 2022-11-15 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizapp2', '0014_remove_quizquestioncollection_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='collection',
            field=models.ManyToManyField(blank=True, related_name='collection_questions', to='Quizapp2.quizquestioncollection'),
        ),
    ]
