# Generated by Django 4.1.3 on 2023-01-17 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizapp2', '0014_alter_trendingarchive_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='trendingarchive',
            name='created_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
