# Generated by Django 4.1.3 on 2023-11-21 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quizapp2', '0015_trendingarchive_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trendingarchive',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Trending Topics Archives'},
        ),
    ]
