# Generated by Django 4.1.3 on 2024-03-02 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizapp2', '0016_alter_trendingarchive_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='questions_attempted',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
