# Generated by Django 4.1.3 on 2024-03-03 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizapp2', '0017_student_questions_attempted'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='accuracy_score',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=5),
            preserve_default=False,
        ),
    ]
