# Generated by Django 4.1.3 on 2022-11-17 06:27

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Quizapp2', '0017_quillpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='creamcards',
            name='rich_text_body',
            field=django_quill.fields.QuillField(blank=True, null=True),
        ),
    ]
