# Generated by Django 4.1.3 on 2022-11-17 06:29

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Quizapp2', '0018_creamcards_rich_text_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creamcards',
            name='rich_text_body',
        ),
        migrations.AlterField(
            model_name='creamcards',
            name='body',
            field=django_quill.fields.QuillField(blank=True, null=True),
        ),
    ]
