# Generated by Django 4.1.3 on 2024-03-07 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizapp2', '0018_student_accuracy_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
