# Generated by Django 4.1.3 on 2022-11-17 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizapp2', '0019_remove_creamcards_rich_text_body_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuillPost',
        ),
        migrations.AlterField(
            model_name='creamcards',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
