# Generated by Django 4.1.3 on 2022-11-18 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizapp2', '0020_delete_quillpost_alter_creamcards_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creamcards',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
