# Generated by Django 4.1.3 on 2024-03-28 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizapp2', '0020_student_correct_attempts_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='correct_attempts_count',
        ),
        migrations.RemoveField(
            model_name='student',
            name='incorrect_attempts_count',
        ),
        migrations.AddField(
            model_name='student',
            name='correct_incorrect_data',
            field=models.CharField(default='1,1', max_length=20),
        ),
    ]
