# Generated by Django 4.1.3 on 2022-11-18 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizapp2', '0021_alter_creamcards_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreamCardsTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('body', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Cream Cards Test',
            },
        ),
    ]
