# Generated by Django 4.1.3 on 2024-04-18 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quizapp2', '0021_remove_student_correct_attempts_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='accuracy_score',
        ),
        migrations.RemoveField(
            model_name='student',
            name='questions_attempted',
        ),
    ]
