# Generated by Django 4.1.3 on 2022-11-18 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Quizapp2', '0022_creamcardstest'),
    ]

    operations = [
        migrations.AddField(
            model_name='creamcardstest',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Quizapp2.authors'),
        ),
        migrations.AddField(
            model_name='creamcardstest',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='creamcardstest',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Quizapp2.subjects'),
        ),
        migrations.AddField(
            model_name='creamcardstest',
            name='url',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
    ]
