# Generated by Django 4.1.3 on 2024-04-18 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizapp2', '0022_remove_student_accuracy_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='accuracy_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
