# Generated by Django 4.1.3 on 2024-04-18 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quizapp2', '0023_student_accuracy_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='last_updated',
        ),
    ]
