# Generated by Django 4.1.3 on 2022-11-18 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Quizapp2', '0023_creamcardstest_author_creamcardstest_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreamCardsTest2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(null=True)),
                ('url', models.CharField(max_length=1500)),
                ('title', models.CharField(max_length=500)),
                ('body', models.TextField(blank=True, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Quizapp2.authors')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Quizapp2.subjects')),
            ],
            options={
                'verbose_name_plural': 'Cream Cards',
            },
        ),
    ]
