# Generated by Django 4.1.3 on 2024-04-24 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizapp2', '0024_remove_student_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='cards_read',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='correct_incorrect_data',
            field=models.CharField(default='1,2,3', max_length=20),
        ),
    ]
