# Generated by Django 4.1.3 on 2022-11-18 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quizapp2', '0024_creamcardstest2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CreamCardsTest2',
        ),
    ]
