# Generated by Django 4.1.3 on 2022-11-18 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quizapp2', '0025_delete_creamcardstest2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creamcards',
            old_name='url',
            new_name='ImageURL',
        ),
    ]
