# Generated by Django 4.1.3 on 2024-06-03 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizapp2', '0025_student_cards_read_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCardButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(null=True)),
                ('ImageURL', models.CharField(max_length=1500)),
                ('title', models.CharField(max_length=500)),
                ('body', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Blog Button Card',
            },
        ),
    ]
