# Generated by Django 4.1.3 on 2022-11-21 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quizapp2', '0029_alter_quizquestion_correctcount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizquestion',
            name='correctCount',
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='inCorrectCount',
        ),
    ]
