# Generated by Django 4.1.3 on 2022-11-21 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizapp2', '0030_remove_quizquestion_correctcount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='correctCount',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='inCorrectCount',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
