# Generated by Django 4.1.3 on 2022-11-24 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizapp2', '0031_quizquestion_correctcount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestioncollection',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
