# Generated by Django 4.1.3 on 2022-11-24 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizapp2', '0032_quizquestioncollection_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizquestioncollection',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
