# Generated by Django 4.1.3 on 2022-11-25 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Quizapp2', '0034_alter_quizquestioncollection_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='creamcards',
            name='related_quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Quizapp2.quizquestioncollection'),
        ),
    ]
