# Generated by Django 4.1.3 on 2022-12-07 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quizapp2', '0035_creamcards_related_quiz'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CreamCardsTest',
        ),
    ]
