# Generated by Django 4.1.3 on 2022-12-12 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Quizapp2', '0037_alter_quizquestion_collection_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizquestion',
            name='collection',
            field=models.ManyToManyField(blank=True, related_name='collection_questions', to='Quizapp2.quizquestioncollection'),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_questions', to='Quizapp2.subjects'),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_questions', to='Quizapp2.topic'),
        ),
    ]
