# Generated by Django 4.1.3 on 2022-12-12 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Quizapp2', '0039_alter_quizquestion_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizquestion',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Quizapp2.topic'),
        ),
    ]
