# Generated by Django 4.1.3 on 2022-12-14 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quizapp2', '0042_alter_customer_options_customer_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
